#!/usr/bin/env python3
"""Generate and run translated test harnesses for a constrained tests.py format."""

from __future__ import annotations

import argparse
import ast
import inspect
import io
import json
import keyword
import os
import re
import runpy
import shutil
import subprocess
import sys
import tempfile
import textwrap
from collections import Counter, defaultdict
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any


SUPPORTED_LANGS = {
    "python": "tester.py",
    "javascript": "tester.js",
    "typescript": "tester.ts",
}
METADATA_MARKER = "BABEL_CODE_GOAT_METADATA:"
METADATA_VERSION = 1
ERROR_RESULT = {"status": "error", "passed": [], "failed": []}
EXPECT_RE = re.compile(r"#\s*(expect_stdout|expect_stderr):\s*(.+)\s*$")


class DiscoveryError(Exception):
    """Raised when tests.py cannot be interpreted as the supported subset."""


class MetadataError(Exception):
    """Raised when generated tester metadata is absent or invalid."""


@dataclass(frozen=True)
class PendingTest:
    line: int
    kind: str
    args: list[Any]
    expected: Any = None
    expect_stdout: str | None = None
    expect_stderr: str | None = None


@dataclass(frozen=True)
class TestCase:
    id: str
    line: int
    kind: str
    args: list[Any]
    expected: Any = None
    expect_stdout: str | None = None
    expect_stderr: str | None = None


def tester_filename(lang: str) -> str:
    return SUPPORTED_LANGS[lang]


def is_supported_lang(lang: str) -> bool:
    return lang in SUPPORTED_LANGS


def is_valid_entrypoint(entrypoint: str) -> bool:
    return entrypoint.isidentifier() and not keyword.iskeyword(entrypoint)


def json_line(result: dict[str, Any]) -> str:
    return json.dumps(result, separators=(",", ":"))


def print_json_result(result: dict[str, Any]) -> None:
    print(json_line(result))


def status_exit_code(status: str) -> int:
    return {"pass": 0, "fail": 1, "error": 2}[status]


def error_result() -> dict[str, Any]:
    return {"status": "error", "passed": [], "failed": []}


def render_tester(lang: str, entrypoint: str) -> str:
    metadata = {
        "version": METADATA_VERSION,
        "entrypoint": entrypoint,
        "lang": lang,
    }
    prefix = "#" if lang == "python" else "//"
    return (
        f"{prefix} Generated by babel_code_goat.py.\n"
        f"{prefix} {METADATA_MARKER} {json_line(metadata)}\n"
    )


def write_atomic(path: Path, content: str) -> None:
    tmp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=str(path.parent),
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as tmp:
            tmp_name = tmp.name
            tmp.write(content)
        os.replace(tmp_name, path)
    finally:
        if tmp_name is not None:
            try:
                os.unlink(tmp_name)
            except FileNotFoundError:
                pass


def read_tester_metadata(path: Path) -> dict[str, Any]:
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if METADATA_MARKER in line:
                payload = line.split(METADATA_MARKER, 1)[1].strip()
                data = json.loads(payload)
                if not isinstance(data, dict):
                    raise MetadataError("metadata is not an object")
                if data.get("version") != METADATA_VERSION:
                    raise MetadataError("unsupported metadata version")
                entrypoint = data.get("entrypoint")
                lang = data.get("lang")
                if not isinstance(entrypoint, str) or not is_valid_entrypoint(entrypoint):
                    raise MetadataError("invalid entrypoint metadata")
                if lang not in SUPPORTED_LANGS:
                    raise MetadataError("invalid language metadata")
                return data
    except (OSError, json.JSONDecodeError) as exc:
        raise MetadataError(str(exc)) from exc
    raise MetadataError("metadata marker not found")


def validate_value(value: Any) -> Any:
    if value is None or isinstance(value, bool):
        return value
    if isinstance(value, (int, float, str)) and not isinstance(value, bool):
        return value
    if isinstance(value, list):
        return [validate_value(item) for item in value]
    if isinstance(value, tuple):
        return tuple(validate_value(item) for item in value)
    if isinstance(value, dict):
        validated: dict[str, Any] = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise DiscoveryError("dictionary keys must be strings")
            validated[key] = validate_value(item)
        return validated
    raise DiscoveryError(f"unsupported literal value: {value!r}")


def parse_literal(node: ast.AST) -> Any:
    try:
        value = ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError) as exc:
        raise DiscoveryError("unsupported non-literal value") from exc
    return validate_value(value)


def parse_expectation_value(raw: str, line_no: int) -> str:
    try:
        value = ast.literal_eval(raw)
    except (ValueError, SyntaxError) as exc:
        raise DiscoveryError(f"invalid output expectation at line {line_no}") from exc
    if not isinstance(value, str):
        raise DiscoveryError(f"output expectation at line {line_no} must be a string")
    return value


class TestDiscoverer:
    def __init__(self, entrypoint: str, source_lines: list[str]) -> None:
        self.entrypoint = entrypoint
        self.source_lines = source_lines
        self.pending: list[PendingTest] = []

    def discover(self, tree: ast.Module) -> list[TestCase]:
        self.visit_body(tree.body)
        return assign_test_ids(self.pending)

    def visit_body(self, body: list[ast.stmt]) -> None:
        for stmt in body:
            if isinstance(stmt, ast.FunctionDef):
                self.visit_function(stmt)
            elif isinstance(stmt, ast.Assert):
                self.visit_assert(stmt)
            elif isinstance(stmt, ast.Try):
                self.visit_raise_expectation(stmt)
            else:
                raise DiscoveryError(
                    f"unsupported statement at line {getattr(stmt, 'lineno', '?')}"
                )

    def visit_function(self, stmt: ast.FunctionDef) -> None:
        if stmt.decorator_list:
            raise DiscoveryError(f"decorators are unsupported at line {stmt.lineno}")
        self.visit_body(stmt.body)

    def visit_assert(self, stmt: ast.Assert) -> None:
        if stmt.msg is not None:
            raise DiscoveryError(f"assert messages are unsupported at line {stmt.lineno}")

        test = stmt.test
        if isinstance(test, ast.Compare):
            if len(test.ops) != 1 or len(test.comparators) != 1:
                raise DiscoveryError(f"unsupported comparison at line {stmt.lineno}")
            args = self.parse_entrypoint_call(test.left, stmt.lineno)
            expected = parse_literal(test.comparators[0])
            if isinstance(test.ops[0], ast.Eq):
                self.add_test(stmt.lineno, "eq", args, expected)
                return
            if isinstance(test.ops[0], ast.NotEq):
                self.add_test(stmt.lineno, "ne", args, expected)
                return
            raise DiscoveryError(f"unsupported comparison operator at line {stmt.lineno}")

        if isinstance(test, ast.UnaryOp) and isinstance(test.op, ast.Not):
            args = self.parse_entrypoint_call(test.operand, stmt.lineno)
            self.add_test(stmt.lineno, "not", args)
            return

        if isinstance(test, ast.Call):
            args = self.parse_entrypoint_call(test, stmt.lineno)
            self.add_test(stmt.lineno, "truthy", args)
            return

        raise DiscoveryError(f"unsupported assertion at line {stmt.lineno}")

    def visit_raise_expectation(self, stmt: ast.Try) -> None:
        if stmt.orelse or stmt.finalbody:
            raise DiscoveryError(f"unsupported try block at line {stmt.lineno}")
        if len(stmt.body) != 2:
            raise DiscoveryError(f"raise expectation requires two try statements at line {stmt.lineno}")

        call_stmt, assert_stmt = stmt.body
        if not isinstance(call_stmt, ast.Expr):
            raise DiscoveryError(f"raise expectation must call entrypoint at line {stmt.lineno}")
        args = self.parse_entrypoint_call(call_stmt.value, stmt.lineno)

        if not isinstance(assert_stmt, ast.Assert):
            raise DiscoveryError(f"raise expectation must assert False at line {stmt.lineno}")
        if assert_stmt.msg is not None:
            raise DiscoveryError(f"assert messages are unsupported at line {assert_stmt.lineno}")
        if not (
            isinstance(assert_stmt.test, ast.Constant)
            and assert_stmt.test.value is False
        ):
            raise DiscoveryError(f"raise expectation must assert False at line {assert_stmt.lineno}")

        if len(stmt.handlers) != 1:
            raise DiscoveryError(f"raise expectation needs one handler at line {stmt.lineno}")
        handler = stmt.handlers[0]
        if not (
            isinstance(handler.type, ast.Name)
            and handler.type.id == "Exception"
            and handler.name is None
            and len(handler.body) == 1
            and isinstance(handler.body[0], ast.Pass)
        ):
            raise DiscoveryError(f"raise expectation must catch Exception and pass at line {stmt.lineno}")

        self.add_test(stmt.lineno, "raises", args)

    def parse_entrypoint_call(self, node: ast.AST, line_no: int) -> list[Any]:
        if not isinstance(node, ast.Call):
            raise DiscoveryError(f"expected entrypoint call at line {line_no}")
        if not isinstance(node.func, ast.Name) or node.func.id != self.entrypoint:
            raise DiscoveryError(f"expected call to {self.entrypoint} at line {line_no}")
        if node.keywords:
            raise DiscoveryError(f"keyword arguments are unsupported at line {line_no}")
        return [parse_literal(arg) for arg in node.args]

    def add_test(
        self,
        line_no: int,
        kind: str,
        args: list[Any],
        expected: Any = None,
    ) -> None:
        expectations = self.expectations_for(line_no)
        self.pending.append(
            PendingTest(
                line=line_no,
                kind=kind,
                args=args,
                expected=expected,
                expect_stdout=expectations.get("expect_stdout"),
                expect_stderr=expectations.get("expect_stderr"),
            )
        )

    def expectations_for(self, test_line: int) -> dict[str, str]:
        expectations: dict[str, str] = {}
        line_no = test_line - 1
        while line_no >= 1:
            text = self.source_lines[line_no - 1].strip()
            if not text:
                break
            if not text.startswith("#"):
                break
            match = EXPECT_RE.fullmatch(text)
            if match is None:
                if text.startswith("# expect_stdout:") or text.startswith("# expect_stderr:"):
                    raise DiscoveryError(f"invalid output expectation at line {line_no}")
                break
            key = match.group(1)
            if key in expectations:
                raise DiscoveryError(f"duplicate {key} expectation at line {line_no}")
            expectations[key] = parse_expectation_value(match.group(2), line_no)
            line_no -= 1
        return expectations


def assign_test_ids(pending: list[PendingTest]) -> list[TestCase]:
    counts = Counter(test.line for test in pending)
    seen: defaultdict[int, int] = defaultdict(int)
    cases: list[TestCase] = []
    for test in pending:
        base = f"tests.py:{test.line}"
        if counts[test.line] > 1:
            index = seen[test.line]
            seen[test.line] += 1
            test_id = f"{base}#{index}"
        else:
            test_id = base
        cases.append(
            TestCase(
                id=test_id,
                line=test.line,
                kind=test.kind,
                args=test.args,
                expected=test.expected,
                expect_stdout=test.expect_stdout,
                expect_stderr=test.expect_stderr,
            )
        )
    return cases


def discover_tests(tests_dir: Path | str, entrypoint: str) -> list[TestCase]:
    tests_path = Path(tests_dir) / "tests.py"
    if not tests_path.is_file():
        raise DiscoveryError("tests.py is required")
    try:
        source = tests_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename="tests.py")
    except (OSError, SyntaxError) as exc:
        raise DiscoveryError("cannot read or parse tests.py") from exc
    return TestDiscoverer(entrypoint, source.splitlines()).discover(tree)


def make_jsonable(value: Any) -> Any:
    if isinstance(value, tuple):
        return [make_jsonable(item) for item in value]
    if isinstance(value, list):
        return [make_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {key: make_jsonable(item) for key, item in value.items()}
    return value


def case_to_json(case: TestCase) -> dict[str, Any]:
    return {
        "id": case.id,
        "kind": case.kind,
        "args": make_jsonable(case.args),
        "expected": make_jsonable(case.expected),
        "expect_stdout": case.expect_stdout,
        "expect_stderr": case.expect_stderr,
    }


def run_python_case(solution_path: Path, entrypoint: str, case: TestCase) -> bool:
    payload = {
        "solution_path": str(solution_path),
        "entrypoint": entrypoint,
        "case": {
            "kind": case.kind,
            "args": case.args,
            "expected": case.expected,
            "expect_stdout": case.expect_stdout,
            "expect_stderr": case.expect_stderr,
        },
    }
    harness = PYTHON_CASE_RUNNER + "\nPAYLOAD = " + repr(payload) + "\nrun(PAYLOAD)\n"
    try:
        proc = subprocess.run(
            [sys.executable, "-c", harness],
            text=True,
            capture_output=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return parse_subprocess_result(proc)


PYTHON_CASE_RUNNER = r'''
import inspect
import io
import json
import runpy
from contextlib import redirect_stderr, redirect_stdout


def _resolve_callable(namespace, entrypoint):
    direct = namespace.get(entrypoint)
    if callable(direct) and not isinstance(direct, type):
        return direct

    module_name = namespace.get("__name__")
    for value in namespace.values():
        if not isinstance(value, type):
            continue
        if module_name is not None and getattr(value, "__module__", None) != module_name:
            continue
        try:
            raw = inspect.getattr_static(value, entrypoint)
        except AttributeError:
            continue
        if isinstance(raw, (staticmethod, classmethod)):
            candidate = getattr(value, entrypoint)
            if callable(candidate):
                return candidate
        try:
            instance = value()
        except Exception:
            continue
        candidate = getattr(instance, entrypoint, None)
        if callable(candidate):
            return candidate
    raise LookupError("entrypoint not found")


def _matches(case, value, raised):
    kind = case["kind"]
    if kind == "raises":
        return raised is not None and isinstance(raised, Exception)
    if raised is not None:
        return False
    if kind == "eq":
        return value == case["expected"]
    if kind == "ne":
        return value != case["expected"]
    if kind == "truthy":
        return bool(value)
    if kind == "not":
        return not bool(value)
    return False


def run(payload):
    case = payload["case"]
    try:
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            namespace = runpy.run_path(payload["solution_path"])
        function = _resolve_callable(namespace, payload["entrypoint"])
    except BaseException:
        print(json.dumps({"passed": False}, separators=(",", ":")))
        return

    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    value = None
    raised = None
    try:
        with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
            value = function(*case["args"])
    except BaseException as exc:
        raised = exc

    passed = _matches(case, value, raised)
    if case["expect_stdout"] is not None:
        passed = passed and stdout_capture.getvalue() == case["expect_stdout"]
    if case["expect_stderr"] is not None:
        passed = passed and stderr_capture.getvalue() == case["expect_stderr"]
    print(json.dumps({"passed": bool(passed)}, separators=(",", ":")))
'''


NODE_CASE_RUNNER = r'''
const fs = require("fs");
const vm = require("vm");

function emit(passed) {
  process.stdout.write(JSON.stringify({passed: Boolean(passed)}) + "\n");
}

function chunkToString(chunk, encoding) {
  if (Buffer.isBuffer(chunk)) {
    return chunk.toString(typeof encoding === "string" ? encoding : "utf8");
  }
  return String(chunk);
}

function installCapture() {
  let stdout = "";
  let stderr = "";
  const originalStdout = process.stdout.write;
  const originalStderr = process.stderr.write;
  process.stdout.write = function(chunk, encoding, callback) {
    stdout += chunkToString(chunk, encoding);
    if (typeof encoding === "function") {
      encoding();
    }
    if (typeof callback === "function") {
      callback();
    }
    return true;
  };
  process.stderr.write = function(chunk, encoding, callback) {
    stderr += chunkToString(chunk, encoding);
    if (typeof encoding === "function") {
      encoding();
    }
    if (typeof callback === "function") {
      callback();
    }
    return true;
  };
  return {
    restore() {
      process.stdout.write = originalStdout;
      process.stderr.write = originalStderr;
    },
    stdout() {
      return stdout;
    },
    stderr() {
      return stderr;
    },
  };
}

function withCaptureSync(fn) {
  const capture = installCapture();
  try {
    const value = fn();
    return {raised: false, value, stdout: capture.stdout(), stderr: capture.stderr()};
  } catch (error) {
    return {raised: true, error, stdout: capture.stdout(), stderr: capture.stderr()};
  } finally {
    capture.restore();
  }
}

async function withCaptureAsync(fn) {
  const capture = installCapture();
  try {
    const value = await fn();
    return {raised: false, value, stdout: capture.stdout(), stderr: capture.stderr()};
  } catch (error) {
    return {raised: true, error, stdout: capture.stdout(), stderr: capture.stderr()};
  } finally {
    capture.restore();
  }
}

function stripTypeScript(source) {
  return source
    .replace(/^\s*export\s+default\s+/gm, "")
    .replace(/^\s*export\s+(?=(function|class|const|let|var)\b)/gm, "")
    .replace(/:\s*[A-Za-z_$][A-Za-z0-9_$<>,\[\]\s|&?.]*(?=\s*[,)=;{])/g, "")
    .replace(/\s+as\s+[A-Za-z_$][A-Za-z0-9_$<>,\[\]\s|&?.]*/g, "");
}

function classNamesFrom(source) {
  const names = new Set();
  const regex = /(?:^|[^\w$])class\s+([A-Za-z_$][A-Za-z0-9_$]*)/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    names.add(match[1]);
  }
  return [...names];
}

function isIdentifier(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

function isClass(value) {
  return typeof value === "function" && /^class\s/.test(Function.prototype.toString.call(value));
}

function resolveFromClass(cls, entrypoint) {
  if (typeof cls !== "function") {
    return null;
  }
  if (typeof cls[entrypoint] === "function") {
    return cls[entrypoint].bind(cls);
  }
  try {
    const instance = new cls();
    if (typeof instance[entrypoint] === "function") {
      return instance[entrypoint].bind(instance);
    }
  } catch (_) {
  }
  return null;
}

function resolveCallable(solutionModule, context, entrypoint) {
  const exported = solutionModule.exports;
  if (exported && typeof exported === "object" && typeof exported[entrypoint] === "function") {
    return exported[entrypoint].bind(exported);
  }
  if (typeof exported === "function") {
    const fromClass = resolveFromClass(exported, entrypoint);
    if (fromClass) {
      return fromClass;
    }
    if (!isClass(exported)) {
      return exported;
    }
  }

  const exposed = context.__bcg_exports || {direct: undefined, classes: []};
  if (typeof exposed.direct === "function") {
    return exposed.direct;
  }
  for (const cls of exposed.classes || []) {
    const fromClass = resolveFromClass(cls, entrypoint);
    if (fromClass) {
      return fromClass;
    }
  }
  throw new Error("entrypoint not found");
}

function deepEqual(left, right) {
  if (Object.is(left, right)) {
    return true;
  }
  if (Array.isArray(left) || Array.isArray(right)) {
    if (!Array.isArray(left) || !Array.isArray(right) || left.length !== right.length) {
      return false;
    }
    return left.every((item, index) => deepEqual(item, right[index]));
  }
  if (
    left !== null &&
    right !== null &&
    typeof left === "object" &&
    typeof right === "object"
  ) {
    const leftKeys = Object.keys(left).sort();
    const rightKeys = Object.keys(right).sort();
    if (!deepEqual(leftKeys, rightKeys)) {
      return false;
    }
    return leftKeys.every((key) => deepEqual(left[key], right[key]));
  }
  return false;
}

function pyTruthy(value) {
  if (value === null || value === undefined || value === false) {
    return false;
  }
  if (typeof value === "number") {
    return value !== 0 && !Number.isNaN(value);
  }
  if (typeof value === "string" || Array.isArray(value)) {
    return value.length > 0;
  }
  if (typeof value === "object") {
    return Object.keys(value).length > 0;
  }
  return true;
}

function assertionMatches(testCase, callResult) {
  if (testCase.kind === "raises") {
    return callResult.raised;
  }
  if (callResult.raised) {
    return false;
  }
  if (testCase.kind === "eq") {
    return deepEqual(callResult.value, testCase.expected);
  }
  if (testCase.kind === "ne") {
    return !deepEqual(callResult.value, testCase.expected);
  }
  if (testCase.kind === "truthy") {
    return pyTruthy(callResult.value);
  }
  if (testCase.kind === "not") {
    return !pyTruthy(callResult.value);
  }
  return false;
}

(async function main() {
  try {
    const solutionPath = process.env.BCG_SOLUTION_PATH;
    const entrypoint = process.env.BCG_ENTRYPOINT;
    const language = process.env.BCG_LANG;
    const testCase = JSON.parse(process.env.BCG_CASE);
    let source = fs.readFileSync(solutionPath, "utf8");
    if (language === "typescript") {
      source = stripTypeScript(source);
    }

    const solutionModule = {exports: {}};
    const context = {
      console,
      require,
      process,
      Buffer,
      setTimeout,
      clearTimeout,
      module: solutionModule,
      exports: solutionModule.exports,
    };
    context.globalThis = context;
    const classNames = classNamesFrom(source);
    const directExpr = isIdentifier(entrypoint)
      ? `(typeof ${entrypoint} !== "undefined" ? ${entrypoint} : undefined)`
      : "undefined";
    const classExprs = classNames
      .filter(isIdentifier)
      .map((name) => `(typeof ${name} !== "undefined" ? ${name} : undefined)`);
    const expose = `\n;globalThis.__bcg_exports = {direct: ${directExpr}, classes: [${classExprs.join(",")}]};`;

    vm.createContext(context);
    const loadResult = withCaptureSync(() => vm.runInContext(source + expose, context, {filename: solutionPath}));
    if (loadResult.raised) {
      emit(false);
      return;
    }

    const callable = resolveCallable(solutionModule, context, entrypoint);
    const callResult = await withCaptureAsync(() => callable(...testCase.args));
    let passed = assertionMatches(testCase, callResult);
    if (testCase.expect_stdout !== null) {
      passed = passed && callResult.stdout === testCase.expect_stdout;
    }
    if (testCase.expect_stderr !== null) {
      passed = passed && callResult.stderr === testCase.expect_stderr;
    }
    emit(passed);
  } catch (_) {
    emit(false);
  }
})();
'''


def run_node_case(solution_path: Path, entrypoint: str, lang: str, case: TestCase) -> bool:
    node_path = shutil.which("node")
    if node_path is None:
        return False
    env = os.environ.copy()
    env.update(
        {
            "BCG_SOLUTION_PATH": str(solution_path),
            "BCG_ENTRYPOINT": entrypoint,
            "BCG_LANG": lang,
            "BCG_CASE": json_line(case_to_json(case)),
        }
    )
    try:
        proc = subprocess.run(
            [node_path, "-"],
            input=NODE_CASE_RUNNER,
            text=True,
            capture_output=True,
            env=env,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return parse_subprocess_result(proc)


def parse_subprocess_result(proc: subprocess.CompletedProcess[str]) -> bool:
    if proc.returncode != 0:
        return False
    lines = [line for line in proc.stdout.splitlines() if line.strip()]
    if not lines:
        return False
    try:
        data = json.loads(lines[-1])
    except json.JSONDecodeError:
        return False
    return data.get("passed") is True


def execute_case(solution_path: Path, lang: str, entrypoint: str, case: TestCase) -> bool:
    if lang == "python":
        return run_python_case(solution_path, entrypoint, case)
    if lang in {"javascript", "typescript"}:
        return run_node_case(solution_path, entrypoint, lang, case)
    return False


def aggregate_results(
    solution_path: Path,
    lang: str,
    entrypoint: str,
    cases: list[TestCase],
) -> dict[str, Any]:
    passed: list[str] = []
    failed: list[str] = []
    for case in cases:
        if execute_case(solution_path, lang, entrypoint, case):
            passed.append(case.id)
        else:
            failed.append(case.id)
    status = "pass" if not failed else "fail"
    return {"status": status, "passed": passed, "failed": failed}


def command_generate(args: argparse.Namespace) -> int:
    lang = args.lang
    tests_dir = Path(args.tests_dir)

    if not is_supported_lang(lang):
        print(f"unsupported language: {lang}", file=sys.stderr)
        return 2
    if not is_valid_entrypoint(args.entrypoint):
        print("invalid entrypoint", file=sys.stderr)
        return 2
    if not tests_dir.is_dir():
        print("tests_dir must be an existing directory", file=sys.stderr)
        return 2

    try:
        discover_tests(tests_dir, args.entrypoint)
        content = render_tester(lang, args.entrypoint)
    except DiscoveryError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    try:
        write_atomic(tests_dir / tester_filename(lang), content)
    except OSError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    return 0


def command_test(args: argparse.Namespace) -> int:
    lang = args.lang
    if not is_supported_lang(lang):
        print_json_result(error_result())
        return 2

    tests_dir = Path(args.tests_dir)
    tester_path = tests_dir / tester_filename(lang)
    if not tester_path.is_file():
        print_json_result(error_result())
        return 2

    try:
        metadata = read_tester_metadata(tester_path)
    except MetadataError:
        print_json_result(error_result())
        return 2
    if metadata["lang"] != lang:
        print_json_result(error_result())
        return 2

    entrypoint = metadata["entrypoint"]
    try:
        cases = discover_tests(tests_dir, entrypoint)
    except DiscoveryError:
        print_json_result(error_result())
        return 2

    result = aggregate_results(Path(args.solution_path), lang, entrypoint, cases)
    print_json_result(result)
    return status_exit_code(result["status"])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="babel_code_goat.py")
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser("generate")
    generate.add_argument("tests_dir")
    generate.add_argument("--entrypoint", required=True)
    generate.add_argument("--lang", required=True)
    generate.set_defaults(func=command_generate)

    test = subparsers.add_parser("test")
    test.add_argument("solution_path")
    test.add_argument("tests_dir")
    test.add_argument("--lang", required=True)
    test.set_defaults(func=command_test)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args, _unknown = parser.parse_known_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
